const API_BASE = "https://api.cloudflare.com/client/v4";

export type DirectUpload = {
  uid: string;
  uploadURL: string;
};

function getCloudflareConfig() {
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
  const apiToken = process.env.CLOUDFLARE_STREAM_API_TOKEN;

  if (!accountId || !apiToken) {
    throw new Error(
      "Cloudflare Stream is not configured. Set CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_STREAM_API_TOKEN.",
    );
  }

  return { accountId, apiToken };
}

/** Creates a one-time upload URL for browser-based direct uploads. */
export async function createDirectUpload(title: string): Promise<DirectUpload> {
  const { accountId, apiToken } = getCloudflareConfig();

  const response = await fetch(
    `${API_BASE}/accounts/${accountId}/stream/direct_upload`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        maxDurationSeconds: 3600,
        meta: { name: title },
      }),
    },
  );

  const data = (await response.json()) as {
    success?: boolean;
    result?: { uid: string; uploadURL: string };
    errors?: Array<{ message?: string }>;
  };

  if (!response.ok || !data.success || !data.result) {
    throw new Error(
      data.errors?.[0]?.message ?? "Failed to create Cloudflare upload URL.",
    );
  }

  return {
    uid: data.result.uid,
    uploadURL: data.result.uploadURL,
  };
}

/** Uploads a video buffer via a one-time direct upload URL. Returns the Stream UID. */
export async function uploadVideoBuffer(buffer: Buffer, title: string): Promise<string> {
  const { uid, uploadURL } = await createDirectUpload(title);
  const form = new FormData();
  form.append("file", new Blob([new Uint8Array(buffer)], { type: "video/mp4" }), "video.mp4");

  const response = await fetch(uploadURL, { method: "POST", body: form });
  if (!response.ok) {
    throw new Error(`Cloudflare upload failed: ${response.status} ${response.statusText}`);
  }

  return uid;
}

/** Default thumbnail URL generated by Cloudflare Stream for a video UID. */
export function streamThumbnailUrl(uid: string): string {
  return `https://videodelivery.net/${uid}/thumbnails/thumbnail.jpg`;
}
